### PR TITLE
support loading stack file addresses from query string

### PR DESCRIPTION
**Pull request by craynic**

### CODE REVIEW

**Comment by walles** [comment]
Hi @craynic, thanks for this!

Could you please add:
* An `example-dump.txt` file with an example thread dump
* A clickable URL to both `index.html` and `README.md` showing how to use the by-query-string feature to analyze the example dump.

  Regards /Johan

**Comment by craynic** [comment]
http://craynic.github.io/tda/index.html?url=stacks/jstack.sample.txt
It could be a demo for this feature.

**Comment by craynic** [comment]
I don't known how to write a readme. Is there any sample or template?

**Comment by walles** [comment]
There's a README.md file at the top of this repo, just add it there!

And to the index.html, since that's what people will see when they just come from Google or wherever.

**Comment by walles** [comment]
I just realized I don't think this works across domains; if I merged this it would only work for URLs on the `spotify.github.io` domain, which would be pretty useless.

For a demo, try this link and watch your Javascript console, note the CORS warning:
<http://craynic.github.io/tda/index.html?url=https://www.kth.se>

Google "CORS" to learn more, but I think it's not possible to get this working cross domains :(.

**Comment by craynic** [comment]
Sorry I'm a little busy these days. In our usage we do serve the script and stack files on a same domain.
Very sorry for that. I will close this PR.

**Pull request closed without merging**
