### PR TITLE
Added a minimal bootstrap theme

### PR DESCRIPTION
**Pull request by indigo423**
I've created a minimal bootstrap theme to have it running as a standalone service for our open source project. Thank you very much great idea and very cool tool.

### CODE REVIEW

**Comment by walles** [comment]
Hi!

Could you please rebase your change on the latest `gh-pages`?

Travis wasn't building things as expected, and I'd like to ensure your changes passes the linter steps before merging anything.

  Regards /Johan

**Comment by indigo423** [comment]
I'll fix the npm test complaints. 

```
Message:
    1 error found in /home/travis/build/spotify/threaddump-analyzer/index.html
[L108:C5] Tag must be paired, no start tag: [ </div> ] (tag-pair)
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: CSSLint failed for stylesheet.css
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by walles** [comment]
Another thing, the files in `css`, are they
- generated? If so, could you add a section to `README.md` describing how to (re)generate them?
- copied from somewhere else? If so, can they be linked from there rather than being part of the project?

**Comment by walles** [comment]
@indigo423, I'm closing this for now since not much has happened lately.

If you still want to get this in, feel free to re-open after making sure the tests pass and clarifying where the `css` files come from.

**Pull request closed without merging**
